Freeman/tests
brighte-labs/spark-web pull request #11
Opened 2022-04-11 10:05 UTC by freemany

<img width="624" alt="Screen Shot 2022-04-11 at 6 21 20 pm" src="https://user-images.githubusercontent.com/1725370/162715710-1d629a2e-a7f0-4b67-8bec-2871c97748b6.png">

2022-04-11 10:30 UTC, lukebennett88 commented on packages/checkbox/src/checkbox.tsx
> +      'aria-describedby': message ?? messageId,
This was correct before.
`aria-describedby` should be provided an id. We're saying if we have a message, the checkbox is described by that message, otherwise it should be `undefined`.

2022-04-11 10:36 UTC, lukebennett88 requested changes

2022-04-11 10:36 UTC, lukebennett88 commented on packages/checkbox/src/checkbox.tsx
> +      'aria-describedby': message ?? messageId,
This was correct before.
`aria-describedby` should be provided an id. We're saying if we have a message, the checkbox is described by that message, otherwise it should be undefined.

2022-04-11 13:02 UTC, freemany commented on packages/checkbox/src/checkbox.tsx
> +      'aria-describedby': message ?? messageId,
Thanks @lukebennett88. Reverted.

2022-04-12 01:05 UTC, freemany commented
> I noticed that we have two Jest configs. Can you delete the old one as part of this PR please @freemany 🙏 https://github.com/brighte-labs/spark-web/blob/freeman/tests/packages/jest.config.js

I can move the inside one from packages to the root, but the displayName should be updated from 'spark-web-packages' to something just `spark-web-monorepo` or `spark-web`?

2022-04-12 01:25 UTC, freemany commented
>

2022-04-12 01:25 UTC, freemany commented
> I noticed that we have two Jest configs. Can you delete the old one as part of this PR please @freemany 🙏 https://github.com/brighte-labs/spark-web/blob/freeman/tests/packages/jest.config.js

We have multi packages setup in our repo, so each package has its own jest config file.

2022-04-12 01:28 UTC, freemany commented
> I noticed that we have two Jest configs. Can you delete the old one as part of this PR please @freemany 🙏 https://github.com/brighte-labs/spark-web/blob/freeman/tests/packages/jest.config.js

We have multi package setup in our repo, each package will have its own jest config file.

2022-04-13 00:28 UTC, nderkim commented
> > I noticed that we have two Jest configs. Can you delete the old one as part of this PR please @freemany 🙏 https://github.com/brighte-labs/spark-web/blob/freeman/tests/packages/jest.config.js
> 
> We have multi project setup in our repo, each project will have its own jest config file.

i think in this case we can just have 1 config at the root since every package should use the same config

2022-04-13 02:34 UTC, freemany commented
> > > I noticed that we have two Jest configs. Can you delete the old one as part of this PR please @freemany 🙏 https://github.com/brighte-labs/spark-web/blob/freeman/tests/packages/jest.config.js
> > 
> > 
> > We have multi project setup in our repo, each project will have its own jest config file.
> 
> i think in this case we can just have 1 config at the root since every package should use the same config

I think we can do that, updated.

2022-04-13 02:37 UTC, freemany commented
> I noticed that we have two Jest configs. Can you delete the old one as part of this PR please @freemany 🙏 https://github.com/brighte-labs/spark-web/blob/freeman/tests/packages/jest.config.js

Updated.

2022-04-13 03:41 UTC, lukebennett88 approved these changes

2022-04-13 05:30 UTC, merged