Fix collapsing gap on Stack in Field
brighte-labs/spark-web pull request #128
Opened 2022-05-24 02:18 UTC by lukebennett88

# Description

[Joss pointed out](https://brighte-au.slack.com/archives/C03C4J5AUHY/p1653353190316019) that the gap property was collapsing in certain scenarios.
This is because the gap was being set to `undefined` if the `labelVisibility` was set to "hidden". We did this because the Box that wraps the label was still appearing in the DOM, and the gap prop was causing space to be reserved for this hidden element (forgetting that the gap was needed for the description and message to be spaced properly.

In my testing, it looks like we can wrap the label with a fragment if labelVisibility is hidden, as Flexbox is smart enough to not reserve space for the `VisuallyHidden` label (I tested this in Brave (Chromium), Firefox and Safari).

## Associated Tickets

- [SPRK-92](https://brighte.atlassian.net/browse/SPRK-92)

2022-05-24 02:21 UTC, lukebennett88 commented on packages/field/src/Field.tsx
> -          {...(data ? buildDataAttributes(data) : null)}
We can just pass the data prop down to the underlying `<Box>` so there is no need to call this function here anymore.

2022-05-24 04:44 UTC, jossmac commented on packages/field/src/Field.tsx
> +        : ({ children }: { children: ReactNode }) => (
Move this out of the main component. Where possible (almost always) we shouldn't create components at runtime.

2022-05-24 04:45 UTC, jossmac requested changes

2022-05-24 04:45 UTC, jossmac commented on packages/field/src/Field.tsx
> +    const LabelWrapper =
Move this out of the main component. Where possible (almost always) we should avoid creating components at runtime.

2022-05-25 02:49 UTC, jossmac approved these changes
LGTM

2022-05-25 02:50 UTC, merged