Fix multiple versions of React
brighte-labs/spark-web pull request #42
Opened 2022-04-26 06:10 UTC by lukebennett88

When using Spark Web with a fresh install of Next.js (which uses React 18 by default) I get the following error:

![PixelSnap 2022-04-26 at 16 03 50@2x](https://user-images.githubusercontent.com/3422401/165232630-b630dc09-11ea-4064-9d85-965246d8f53c.png)

Looks like this is because we're shipping React 17.0.2 with the design system.

To address this by moving React _out_ of our `dependencies`, _into_ our `devDependencies` and adding `"react": ">=17.0.2"` to our `peerDependencies`.

I've also sorted the `package.json` files using [this npx script](https://www.npmjs.com/package/sort-package-json) to  make the find-and-replace a little easier.

2022-04-26 06:14 UTC, JedWatson requested changes
@lukebennett88 can you break this PR up into two: one to clean up the package.json ordering (first) and then a separate one to just fix the dependencies?

hard to review at the moment

2022-04-26 06:14 UTC, lukebennett88 commented
Sure thing @JedWatson

2022-04-26 06:19 UTC, lukebennett88 commented
PR to sort packages here:
https://github.com/brighte-labs/spark-web/pull/43

2022-04-28 03:10 UTC, jesstelford approved these changes

2022-04-28 03:16 UTC, merged