Feature/loader component
brighte-labs/spark-web pull request #44
Opened 2022-04-26 07:54 UTC by matildaPan

<img width="791" alt="Screen Shot 2022-04-26 at 5 53 13 pm" src="https://user-images.githubusercontent.com/5338397/165250110-596479d3-2bd8-4542-ac7e-bbda52db632e.png">

2022-04-26 22:44 UTC, lukebennett88 commented
Needs a changeset 👍

2022-04-26 22:47 UTC, lukebennett88 commented
Wondering if `Loading` or `Spinner` might be a better name than `Loader`?
"Loader" to me is a little confusing as it seems to imply that it is responsible for loading data.

2022-04-27 01:05 UTC, justinfaynhan commented on .changeset/sweet-hornets-whisper.md
> +'@spark-web/loader': major
**question**: does @spark-web/icon need a minor bump?

2022-04-27 02:18 UTC, lukebennett88 requested changes

2022-04-27 06:04 UTC, matildaPan commented on packages/loader/src/Loader.tsx
> +export function Loader({ tone, size = 'xxsmall' }: LoaderProps) {
can't do it , if we default the tone , Spinner doesn't inherit from parent DOM colour , such as colour of button . 
we need to fix 
`packages/button/src/resolveButtonChildren.tsx`
so the child element can have right colour

2022-04-27 06:59 UTC, lukebennett88 approved these changes

2022-04-27 07:15 UTC, merged