Feature/search optimisation
brighte-labs/spark-web pull request #72
Opened 2022-05-06 00:07 UTC by matildaPan

2022-05-09 04:31 UTC, matildaPan commented on docs/components/header.tsx
> +const SearchResultsContainer = ({
we will replace SearchResultsContainer with Autocomplete box later

2022-05-09 06:00 UTC, matildaPan commented on docs/next.config.mjs
> +    this.field('title', { boost: 100 });
based on our markdown , title takes more weight

2022-05-10 00:26 UTC, freemany commented on docs/components/header.tsx
> +    searchIndexPromise ??
I think it won't reach here line 165 but early return in 162.
we can try:
`if (lunrIndex) {`
`   return lunrIndex;`
`}`
`try {`
    `    const [jsonIndex, lunr] = await Promise.all([import('../cache/search-index.json'), import('lunr')]);`
    `   lunrIndex = lunr.default.Index.load(jsonIndex);`
`} catch (error) {`
    `   console.error(error);`
`}`
`return lunrIndex;`

2022-05-10 00:44 UTC, matildaPan commented on docs/components/header.tsx
> +    searchIndexPromise ??
It will reach here. At the first,  searchIndexPromise is `undefined`, so searchIndexPromise = Promis.all(search-index, lunr). On the second time, searchIndexPromise is unresolved promise, so it won't try to import async, hence we optimise the import for only just once.
Your code will work as well, but the downside is it may try to import more than once

2022-05-10 05:33 UTC, nderkim commented on .changeset/clean-eels-peel.md
> +'@spark-web/docs': minor
@lukebennett88 said we don't version docs

2022-05-10 05:55 UTC, nderkim commented on docs/package.json
> +    "contentlayer": "^0.2.4",
should these be in devDependencies?

2022-05-10 05:56 UTC, nderkim commented on docs/package.json
> +    "esbuild": "^0.14.38",
why is esbuild here?

2022-05-10 05:57 UTC, nderkim commented on docs/package.json
> +    "mdx-bundler": "^9.0.0",
same here

2022-05-10 06:01 UTC, lukebennett88 commented on docs/package.json
> +    "contentlayer": "^0.2.4",
Yep, if we rebase from main that should already be fixed (although I spotted a few other dependencies that should probably be in devDependencies instead)

2022-05-10 06:04 UTC, lukebennett88 commented on docs/package.json
> +    "esbuild": "^0.14.38",
MDX Bundler needs it, but turns out we didn't need that either (Contentlayer comes with something for this, but just required some config to get working).
I've already fixed this in a PR yesterday.

2022-05-10 06:05 UTC, nderkim commented on packages/box/src/useBoxStyles.ts
> +  top?: ResponsiveProp<0 | 100>;
@lukebennett88 ☝️

2022-05-10 06:08 UTC, lukebennett88 commented on packages/box/src/useBoxStyles.ts
> +  top?: ResponsiveProp<0 | 100>;
Yeah we should be using css function from Emotion instead of extending the accepted props.

2022-05-10 06:18 UTC, nderkim approved these changes

2022-05-10 06:22 UTC, lukebennett88 requested changes
We're going to need a working Autocomplete before we can merge this.

2022-05-10 06:24 UTC, lukebennett88 commented on docs/components/header.tsx
> +let lunrIndex: any;
Any chance we can get rid of this `any`.

2022-05-10 06:28 UTC, freemany commented on docs/components/header.tsx
> +    throw getSearchInstance();
Is this thrown error got caught?

2022-05-10 06:32 UTC, freemany commented on docs/components/header.tsx
> +        } else {
`else` can be removed

2022-05-10 06:45 UTC, matildaPan commented on docs/components/header.tsx
> +    throw getSearchInstance();
it is React Suspense syntax

2022-05-10 06:46 UTC, matildaPan commented on docs/components/header.tsx
> +        } else {
no it can't be removed , it renders different UI component

2022-05-10 22:22 UTC, lukebennett88 commented on docs/components/header.tsx
> +    throw getSearchInstance();
Yep, this is how Suspense works.
I'm not an expert from what I know you `throw` a Promise and React will render the fallback in the suspense boundary. Once the Promise has resolved the whole component renders.

2022-05-11 00:33 UTC, freemany commented on docs/components/header.tsx
> +        } else {
I meant:
`if (match?.[1].title) {
          return ...
  }`
  `return ...;`

2022-05-16 05:51 UTC, lukebennett88 commented on docs/components/header.tsx
>  export function Header() {
I've broken the Header up into smaller components to make more readable

2022-05-16 07:07 UTC, lukebennett88 approved these changes

2022-05-16 07:08 UTC, merged