SPRK-10 Add combobox
brighte-labs/spark-web pull request #78
Opened 2022-05-09 03:28 UTC by nderkim

2022-05-09 07:19 UTC, matildaPan commented on packages/combobox/src/combobox.tsx
> +          ...selectTheme.colors,
should we move these colours below to token , so we can have single point of truth ?

2022-05-09 07:53 UTC, nderkim commented on packages/combobox/src/combobox.tsx
> +          ...selectTheme.colors,
Our `color` tokens aren't exported so we don't have access to them from this component.
I could do: `import { colors } from '@spark-web/theme/src/colors';` (but we don't publish `/src` with our packages)
or `import { colors } from '../../theme/src/colors';` (but preconstruct gives me an error about importing relative paths outside the package)

2022-05-09 23:42 UTC, lukebennett88 commented on packages/combobox/src/combobox.tsx
> +  loading?: boolean;
Nitpick: can we add a JSDoc comment for loading. Hoping we can eventually generate the API docs from this rather than hand-coding.

2022-05-10 01:18 UTC, lukebennett88 commented on packages/combobox/src/combobox.tsx
> +  const customStyles: StylesConfig<Item, boolean, GroupBase<Item>> = {
Nitpick: Can tuck the styling and components away into hooks/functions?
Something like:
```tsx
function useComboboxStyles<Item>({ invalid }: { invalid?: boolean }) {
  const theme = useTheme();
  const [textStyles] = useText({
    baseline: false,
    tone: 'neutral',
    size: 'standard',
    weight: 'regular',
  });
  const focusRingStyles = useFocusRing({ always: true });
  const comboboxStyles: StylesConfig<Item, boolean, GroupBase<Item>> = {
    option: (provided, state) => ({
      ...provided,
      ...textStyles,
      borderRadius: theme.border.radius.small,
      ...(state.isSelected
        ? {
            color: theme.color.foreground.primaryActive,
            backgroundColor: theme.color.background.primaryMuted,
          }
        : {}),
      ...(state.isFocused
        ? {
            backgroundColor: state.isSelected
              ? theme.backgroundInteractions.primaryLowHover
              : theme.color.background.surfaceMuted,

            '> *': {
              color: state.isSelected
                ? theme.color.foreground.primaryHover
                : undefined,
              stroke: state.isSelected
                ? theme.color.foreground.primaryHover
                : undefined,
            },
          }
        : {}),
      ':active': {
        backgroundColor: state.isSelected
          ? theme.backgroundInteractions.positiveLowActive
          : theme.color.background.surfacePressed,

        '> *': {
          color: state.isSelected
            ? theme.color.foreground.primaryActive
            : undefined,
          stroke: state.isSelected
            ? theme.color.foreground.primaryActive
            : undefined,
        },
      },
    }),
    control: (provided, state) => ({
      ...provided,
      ...textStyles,
      ...(state.isFocused
        ? focusRingStyles
        : invalid
        ? {
            borderColor: theme.color.foreground.critical,
          }
        : {}),
    }),
    menu: provided => ({
      ...provided,
      boxShadow: theme.shadow.medium,
      borderRadius: theme.border.radius.medium,
    }),
    menuList: provided => ({
      ...provided,
      padding: theme.spacing.small,
      display: 'flex',
      flexDirection: 'column',
      gap: theme.spacing.xsmall,
    }),
    dropdownIndicator: (provided, state) => ({
      ...provided,
      transitionProperty: 'transform',
      transitionTimingFunction: 'linear',
      transitionDuration: '100ms',
      ...(state.isFocused
        ? {
            transform: 'rotate(180deg)',
          }
        : {}),
    }),
  } as const;
  return comboboxStyles;
}

function useComboboxTheme() {
  const theme = useTheme();
  return (selectTheme: Theme) =>
    ({
      ...selectTheme,
      borderRadius: theme.border.radius.small,
      colors: {
        ...selectTheme.colors,
        // NOTE: these hard-coded colors will be updated in the future once tokens
        // have been revised
        primary: '#00a87b',
        primary75: '#00c28d',
        primary50: '#9acbb8',
        primary25: '#c8eada',
        danger: '#e61e32',
        dangerLight: '#fec1b5',
        neutral0: 'white',
        neutral5: '#fafcfe',
        neutral10: '#f1f4fb',
        neutral20: '#dce1ec',
        neutral30: '#c7cedb',
        // neutral40,
        neutral50: '#98a2b8',
        neutral60: '#646f84',
        neutral70: '#1a2a3a',
        // neutral80,
        // neutral90,
      },
      spacing: {
        baseUnit: theme.spacing.xsmall,
        controlHeight: theme.sizing.medium,
        menuGutter: theme.spacing.xxsmall,
      },
    } as const);
}

const getComboboxComponents = <Item,>(): Partial<
  SelectComponents<Item, false, GroupBase<Item>>
> => {
  return {
    DropdownIndicator: props => (
      <components.DropdownIndicator {...props}>
        <ChevronDownIcon size="xxsmall" tone="muted" />
      </components.DropdownIndicator>
    ),
    IndicatorSeparator: () => null,
    LoadingMessage: props => (
      <components.LoadingMessage {...props}>
        <Box paddingY="large">
          <Spinner size="xsmall" tone="primary" />
        </Box>
      </components.LoadingMessage>
    ),
    NoOptionsMessage: props => (
      <components.NoOptionsMessage {...props}>
        <Box paddingY="large">
          <Text>No matching results</Text>
        </Box>
      </components.NoOptionsMessage>
    ),
  };
};
```

That way the component itself is more readable and it's clearer what the various hooks we call to create these object are used for:

```tsx
export const Combobox = <Item,>({
  placeholder,
  inputValue,
  items: options,
  onChange,
  onInputChange,
  value,
  loading: isLoading,
}: ComboboxProps<Item>) => {
  const {
    disabled: isDisabled,
    invalid,
    id: inputId,
    'aria-describedby': ariaDescribedBy,
  } = useFieldContext();
  const styles = useComboboxStyles<Item>({ invalid });
  const theme = useComboboxTheme();
  const components = getComboboxComponents<Item>();
  const isBrowser = typeof window !== 'undefined';
  const menuPortalTarget = isBrowser ? document.body : undefined;
  
  return (
    <ReactSelect<Item>
      aria-describedby={ariaDescribedBy}
      components={components}
      inputId={inputId}
      inputValue={inputValue}
      isDisabled={isDisabled}
      isLoading={isLoading}
      menuPortalTarget={menuPortalTarget}
      onChange={onChange}
      onInputChange={onInputChange}
      options={options}
      placeholder={placeholder}
      styles={styles}
      theme={theme}
      value={value}
    />
  );
};
```

2022-05-10 01:19 UTC, lukebennett88 commented on packages/combobox/src/index.ts
> +export { Combobox } from './combobox';
Need to export types as well

2022-05-10 01:22 UTC, lukebennett88 commented on packages/combobox/README.md
> +  <Field label="What's your favourite ice cream flavour?">
Nitpick: maybe change the examples so they're not the same as Balance?
Suggestion: 
```tsx
<Field label="What's your Adventure Time character?">
  <Combobox
    placeholder="Select a character"
    items={[
      { label: 'Jake', value: 'jake' },
      { label: 'Finn', value: 'finn' },
      { label: 'BMO', value: 'bmo' },
    ]}
    onChange={value => setValue(value)}
    value={value}
  />
</Field>
```

2022-05-10 01:25 UTC, lukebennett88 commented on packages/combobox/package.json
> +  "module": "dist/spark-web-combobox.esm.js",
Can we add this so we don't ship everything to npm
```json
"files": [
    "dist"
  ],
  ```

2022-05-10 01:27 UTC, lukebennett88 commented on packages/combobox/package.json
> +    "react": "^17.0.2",
We need to move `react` out of `dependencies` and into both `devDependencies` and `peerDependencies`. Otherwise users won't be able to use a different version of React.

2022-05-10 01:30 UTC, lukebennett88 requested changes
We need to shuffle some stuff around in the `package.json` so our users don't have to use the specific version of React that we're using.
Apart from that just a few nitpicks which I've left comments for.

2022-05-10 02:37 UTC, nderkim commented on packages/combobox/README.md
> +  <Field label="What's your favourite ice cream flavour?">
![image](https://user-images.githubusercontent.com/44968616/167531477-def200c7-98e8-4881-b58a-84247078fd88.png)

2022-05-10 06:14 UTC, lukebennett88 commented on packages/combobox/src/react-select-overrides.tsx
> +export const useReactSelectComponentsOverride = <
Nitpick: we're not calling a hook here, so the name probably shouldn't start with `use`.

2022-05-10 06:15 UTC, lukebennett88 commented on packages/combobox/src/react-select-overrides.tsx
> +import { useFocusRing } from '@spark-web/a11y';
Much tidier 💅

2022-05-10 07:11 UTC, nderkim commented on packages/combobox/src/react-select-overrides.tsx
> +import { useFocusRing } from '@spark-web/a11y';
💇

2022-05-10 11:43 UTC, lukebennett88 approved these changes
LGTM 👍

2022-05-10 23:06 UTC, merged