feat: added text area component with corresponding docs
brighte-labs/spark-web pull request #9
Opened 2022-04-11 06:59 UTC by justinfaynhan

2022-04-11 07:06 UTC, matildaPan approved these changes
🎉

2022-04-11 07:15 UTC, lukebennett88 requested changes

2022-04-11 07:15 UTC, lukebennett88 commented on packages/text-area/src/TextArea.tsx
> +    textOverflow: 'ellipsis',
We can remove these, they were specific for the `Select`

2022-04-11 07:15 UTC, lukebennett88 commented on packages/text-area/src/TextArea.tsx
> +      theme.spacing.medium * 2, // paddingX value
Same as above. This was reserving space for the chevron icon for the `Select` so we don't need it.

2022-04-11 07:20 UTC, lukebennett88 commented on packages/text-area/README.md
> +
Happy to approve this as is, but feels a little lite. Would be nice to flesh this out a tiny bit more.

[Balance has a size prop](https://balance.reckon.com/package/textarea#size) @jordangeizer do you think we should do the same?

2022-04-12 06:31 UTC, justinfaynhan commented on packages/text-area/README.md
> +
Added more doc examples regarding text area demonstrating size and weight use cases

2022-04-13 00:59 UTC, lukebennett88 approved these changes

2022-04-13 01:00 UTC, merged